[package]
name = "dister"
authors = ["Jackson Novak <ogloooglooagla@tutanota.com>"]
version = "1.0.1"
edition = "2021"

[profile.bench]
lto = "thin"
debug = 1
strip = false

[profile.release]
debug = 0
lto = true
opt-level = 3
codegen-units = 1
strip = true

[dependencies]
clap = {version = "4.3.19", features = ["derive"]}
colored = "2.0.4"
dirs = "5.0.1"
hostname = "0.3.1"
serde = {version = "1.0.183", features = ["derive"]}
toml = "0.7.6"
users = "0.11.0"
